// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace camera_recorder_pigeon {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class CameraHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Generated class from Pigeon that represents data sent in messages.
class CameraDescription {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit CameraDescription(const std::string& id);

  // Constructs an object setting all fields.
  explicit CameraDescription(
    const std::string& id,
    const std::string* name);

  const std::string& id() const;
  void set_id(std::string_view value_arg);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);


 private:
  static CameraDescription FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CameraHostApi;
  friend class CameraHostApiCodecSerializer;
  std::string id_;
  std::optional<std::string> name_;

};


// Generated class from Pigeon that represents data sent in messages.
class PreviewSize {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PreviewSize(
    int64_t width,
    int64_t height);

  // Constructs an object setting all fields.
  explicit PreviewSize(
    int64_t width,
    int64_t height,
    const int64_t* rotation);

  int64_t width() const;
  void set_width(int64_t value_arg);

  int64_t height() const;
  void set_height(int64_t value_arg);

  const int64_t* rotation() const;
  void set_rotation(const int64_t* value_arg);
  void set_rotation(int64_t value_arg);


 private:
  static PreviewSize FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CameraHostApi;
  friend class CameraHostApiCodecSerializer;
  int64_t width_;
  int64_t height_;
  std::optional<int64_t> rotation_;

};

class CameraHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  CameraHostApiCodecSerializer();
  inline static CameraHostApiCodecSerializer& GetInstance() {
    static CameraHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class CameraHostApi {
 public:
  CameraHostApi(const CameraHostApi&) = delete;
  CameraHostApi& operator=(const CameraHostApi&) = delete;
  virtual ~CameraHostApi() {}
  virtual ErrorOr<flutter::EncodableList> EnumerateCameras() = 0;
  virtual ErrorOr<bool> OpenCamera(const std::string& device_id) = 0;
  virtual ErrorOr<bool> StartPreview() = 0;
  virtual ErrorOr<bool> StopPreview() = 0;
  virtual ErrorOr<bool> StartVideoRecording(
    int64_t camera_id,
    const std::string& file_path) = 0;
  virtual ErrorOr<std::optional<std::string>> StopVideoRecording(int64_t camera_id) = 0;
  virtual std::optional<FlutterError> CloseCamera() = 0;
  virtual ErrorOr<int64_t> GetPreviewTextureId() = 0;
  virtual ErrorOr<PreviewSize> GetPreviewSize() = 0;

  // The codec used by CameraHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `CameraHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    CameraHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    CameraHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  CameraHostApi() = default;

};
}  // namespace camera_recorder_pigeon
#endif  // PIGEON_MESSAGES_G_H_
