// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace camera_recorder_pigeon {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// CameraDescription

CameraDescription::CameraDescription(const std::string& id)
 : id_(id) {}

CameraDescription::CameraDescription(
  const std::string& id,
  const std::string* name)
 : id_(id),
    name_(name ? std::optional<std::string>(*name) : std::nullopt) {}

const std::string& CameraDescription::id() const {
  return id_;
}

void CameraDescription::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string* CameraDescription::name() const {
  return name_ ? &(*name_) : nullptr;
}

void CameraDescription::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CameraDescription::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


EncodableList CameraDescription::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(id_));
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  return list;
}

CameraDescription CameraDescription::FromEncodableList(const EncodableList& list) {
  CameraDescription decoded(
    std::get<std::string>(list[0]));
  auto& encodable_name = list[1];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  return decoded;
}

// PreviewSize

PreviewSize::PreviewSize(
  int64_t width,
  int64_t height)
 : width_(width),
    height_(height) {}

PreviewSize::PreviewSize(
  int64_t width,
  int64_t height,
  const int64_t* rotation)
 : width_(width),
    height_(height),
    rotation_(rotation ? std::optional<int64_t>(*rotation) : std::nullopt) {}

int64_t PreviewSize::width() const {
  return width_;
}

void PreviewSize::set_width(int64_t value_arg) {
  width_ = value_arg;
}


int64_t PreviewSize::height() const {
  return height_;
}

void PreviewSize::set_height(int64_t value_arg) {
  height_ = value_arg;
}


const int64_t* PreviewSize::rotation() const {
  return rotation_ ? &(*rotation_) : nullptr;
}

void PreviewSize::set_rotation(const int64_t* value_arg) {
  rotation_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PreviewSize::set_rotation(int64_t value_arg) {
  rotation_ = value_arg;
}


EncodableList PreviewSize::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(width_));
  list.push_back(EncodableValue(height_));
  list.push_back(rotation_ ? EncodableValue(*rotation_) : EncodableValue());
  return list;
}

PreviewSize PreviewSize::FromEncodableList(const EncodableList& list) {
  PreviewSize decoded(
    list[0].LongValue(),
    list[1].LongValue());
  auto& encodable_rotation = list[2];
  if (!encodable_rotation.IsNull()) {
    decoded.set_rotation(encodable_rotation.LongValue());
  }
  return decoded;
}


CameraHostApiCodecSerializer::CameraHostApiCodecSerializer() {}

EncodableValue CameraHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(CameraDescription::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(PreviewSize::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void CameraHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(CameraDescription)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<CameraDescription>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PreviewSize)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<PreviewSize>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by CameraHostApi.
const flutter::StandardMessageCodec& CameraHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&CameraHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `CameraHostApi` to handle messages through the `binary_messenger`.
void CameraHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  CameraHostApi* api) {
  CameraHostApi::SetUp(binary_messenger, api, "");
}

void CameraHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  CameraHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.enumerateCameras" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->EnumerateCameras();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.openCamera" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          ErrorOr<bool> output = api->OpenCamera(device_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.startPreview" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->StartPreview();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.stopPreview" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->StopPreview();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.startVideoRecording" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_camera_id_arg = args.at(0);
          if (encodable_camera_id_arg.IsNull()) {
            reply(WrapError("camera_id_arg unexpectedly null."));
            return;
          }
          const int64_t camera_id_arg = encodable_camera_id_arg.LongValue();
          const auto& encodable_file_path_arg = args.at(1);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          ErrorOr<bool> output = api->StartVideoRecording(camera_id_arg, file_path_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.stopVideoRecording" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_camera_id_arg = args.at(0);
          if (encodable_camera_id_arg.IsNull()) {
            reply(WrapError("camera_id_arg unexpectedly null."));
            return;
          }
          const int64_t camera_id_arg = encodable_camera_id_arg.LongValue();
          ErrorOr<std::optional<std::string>> output = api->StopVideoRecording(camera_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.closeCamera" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->CloseCamera();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.getPreviewTextureId" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<int64_t> output = api->GetPreviewTextureId();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.camera_recorder.CameraHostApi.getPreviewSize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<PreviewSize> output = api->GetPreviewSize();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue CameraHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue CameraHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace camera_recorder_pigeon
